// Katalog permission default — di-seed ke setiap tenant baru.
// Format key: "<module>.<action>".
export const DEFAULT_PERMISSIONS: { key: string; description: string; module: string }[] = [
  { key: "contacts.create", description: "Buat kontak", module: "contacts" },
  { key: "contacts.read", description: "Lihat kontak", module: "contacts" },
  { key: "contacts.update", description: "Ubah kontak", module: "contacts" },
  { key: "contacts.delete", description: "Hapus kontak", module: "contacts" },
  { key: "deals.create", description: "Buat deal", module: "deals" },
  { key: "deals.read", description: "Lihat deal", module: "deals" },
  { key: "deals.update", description: "Ubah deal", module: "deals" },
  { key: "deals.delete", description: "Hapus deal", module: "deals" },
  { key: "activities.create", description: "Buat aktivitas", module: "activities" },
  { key: "activities.read", description: "Lihat aktivitas", module: "activities" },
  { key: "activities.update", description: "Ubah aktivitas", module: "activities" },
  { key: "activities.delete", description: "Hapus aktivitas", module: "activities" },
  { key: "reports.export", description: "Export laporan", module: "reports" },
  { key: "settings.manage_roles", description: "Kelola role & permission", module: "settings" },
  { key: "settings.manage_billing", description: "Kelola billing", module: "settings" },
  // — ERP/HRM/PM —
  { key: "tasks.create", description: "Buat task project", module: "tasks" },
  { key: "tasks.read", description: "Lihat task project", module: "tasks" },
  { key: "tasks.update", description: "Ubah task project", module: "tasks" },
  { key: "tasks.delete", description: "Hapus task project", module: "tasks" },
  { key: "invoices.create", description: "Buat invoice", module: "invoices" },
  { key: "invoices.read", description: "Lihat invoice", module: "invoices" },
  { key: "invoices.update", description: "Ubah invoice", module: "invoices" },
  { key: "invoices.delete", description: "Hapus invoice", module: "invoices" },
  { key: "projects.create", description: "Buat project", module: "projects" },
  { key: "projects.read", description: "Lihat project", module: "projects" },
  { key: "projects.update", description: "Ubah project", module: "projects" },
  { key: "projects.delete", description: "Hapus project", module: "projects" },
  { key: "accounting.read", description: "Lihat pembukuan", module: "accounting" },
  { key: "accounting.post", description: "Posting jurnal", module: "accounting" },
  { key: "employees.create", description: "Tambah karyawan", module: "employees" },
  { key: "employees.read", description: "Lihat karyawan", module: "employees" },
  { key: "employees.update", description: "Ubah karyawan", module: "employees" },
  { key: "employees.delete", description: "Hapus karyawan", module: "employees" },
  { key: "timetracking.create", description: "Catat waktu kerja", module: "timetracking" },
  { key: "timetracking.read", description: "Lihat catatan waktu", module: "timetracking" },
  { key: "organization.manage", description: "Kelola struktur organisasi", module: "organization" },
  { key: "clients.create", description: "Buat klien", module: "clients" },
  { key: "clients.read", description: "Lihat klien", module: "clients" },
  { key: "clients.update", description: "Ubah klien", module: "clients" },
  { key: "clients.delete", description: "Hapus klien", module: "clients" },
];

export const OWNER_EXCLUDED: string[] = [];
export const ADMIN_EXCLUDED = ["settings.manage_billing"];
export const MEMBER_INCLUDED = [
  "contacts.create",
  "contacts.read",
  "contacts.update",
  "deals.create",
  "deals.read",
  "deals.update",
  "activities.create",
  "activities.read",
  "activities.update",
  "tasks.create",
  "tasks.read",
  "tasks.update",
  "projects.read",
  "timetracking.create",
  "timetracking.read",
  "clients.read",
];
