// Katalog permission CRM: contacts, deals, conversations (WhatsApp),
// campaigns (blasting), tickets, reports, settings.
export const DEFAULT_PERMISSIONS: { key: string; description: string; module: string }[] = [
  { key: "contacts.create", description: "Buat kontak", module: "contacts" },
  { key: "contacts.read", description: "Lihat kontak", module: "contacts" },
  { key: "contacts.update", description: "Ubah kontak", module: "contacts" },
  { key: "contacts.delete", description: "Hapus kontak", module: "contacts" },
  { key: "deals.create", description: "Buat deal", module: "deals" },
  { key: "deals.read", description: "Lihat deal", module: "deals" },
  { key: "deals.update", description: "Ubah deal", module: "deals" },
  { key: "deals.delete", description: "Hapus deal", module: "deals" },
  { key: "activities.create", description: "Buat aktivitas", module: "activities" },
  { key: "activities.read", description: "Lihat aktivitas", module: "activities" },
  { key: "activities.update", description: "Ubah aktivitas", module: "activities" },
  { key: "activities.delete", description: "Hapus aktivitas", module: "activities" },
  { key: "conversations.read", description: "Lihat percakapan", module: "conversations" },
  { key: "conversations.reply", description: "Balas percakapan", module: "conversations" },
  { key: "conversations.assign", description: "Assign & resolve percakapan", module: "conversations" },
  { key: "conversations.manage_channels", description: "Kelola channel WhatsApp", module: "conversations" },
  { key: "campaigns.create", description: "Buat campaign blasting", module: "campaigns" },
  { key: "campaigns.read", description: "Lihat campaign", module: "campaigns" },
  { key: "campaigns.launch", description: "Luncurkan blasting", module: "campaigns" },
  { key: "campaigns.delete", description: "Hapus campaign", module: "campaigns" },
  { key: "tickets.create", description: "Buat tiket", module: "tickets" },
  { key: "tickets.read", description: "Lihat tiket", module: "tickets" },
  { key: "tickets.update", description: "Ubah & balas tiket", module: "tickets" },
  { key: "tickets.delete", description: "Hapus tiket", module: "tickets" },
  { key: "reports.view", description: "Lihat laporan", module: "reports" },
  { key: "reports.export", description: "Export laporan", module: "reports" },
  { key: "settings.manage_roles", description: "Kelola role & permission", module: "settings" },
  { key: "settings.manage_billing", description: "Kelola billing", module: "settings" },
];

export const OWNER_EXCLUDED: string[] = [];
export const ADMIN_EXCLUDED = ["settings.manage_billing"];
export const MEMBER_INCLUDED = [
  "contacts.create",
  "contacts.read",
  "contacts.update",
  "deals.create",
  "deals.read",
  "deals.update",
  "activities.create",
  "activities.read",
  "activities.update",
  "conversations.read",
  "conversations.reply",
  "campaigns.read",
  "tickets.create",
  "tickets.read",
  "tickets.update",
  "reports.view",
];
